sudo: required
language: generic 
services:
    - docker 

before_install:
    - docker build -t cshorne/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cshorne/docker-react npm run test